ClaimBaseTest.Web/Controllers/AdminConsole_Controllers/FunctionMasterController.cs
using CodeGen.Repository.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using CodeGen.Model.FunctionMasterModel;
using CodeGen.Model.CommonFunction;
using X.PagedList;
namespace ClaimBaseTest.Web
{
    public class FunctionMasterController : Controller
    {     // GET: /FunctionMaster/
        int intOut;
        FunctionMasterModel ObjFun = new FunctionMasterModel();
        private const int defaultPageSize =1000;
        private readonly IFuncServiceProvider _functionService;

        public FunctionMasterController(IFuncServiceProvider functionService)
        {

            _functionService = functionService;
        }
        
       public ActionResult AddFunctionMaster()
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                return View();
            //}
            //else
            //{
            //    return RedirectToAction("LogOut", "Home");
            //}
        }
        #region Add Function Master
        [HttpPost]
        public ActionResult AddFunctionMaster(IFormCollection Coll, FunctionMasterModel model, string Command)
        {
            if (Command == "Log")
            {
                //FileLogger fileLogger = new FileLogger();
                //string path = fileLogger.ShowLogFile();
                //ViewData["log"] = path;
                return View();
            }

            if (Command == "Submit")
            {
                try
                {
                    if (ModelState.IsValid)
                    {

                        model.ActionCode = "A";
                        model.FunctionName = Coll["FunctionName"].ToString();
                        model.FileName = Coll["FileName"].ToString();
                        model.Description = Coll["Description"].ToString();
                        if (Coll["CheckBoxAdd"].ToString() == "true,false")
                            model.FAdd = "Add";
                        else
                            model.FAdd = "N";
                        if (Coll["CheckBoxView"].ToString() == "true,false")
                            model.FView = "View";
                        else
                            model.FView = "N";
                        if (Coll["CheckBoxManage"].ToString() == "true,false")
                            model.FManage = "Manage";
                        else
                            model.FManage = "N";
                        model.MailR = Convert.ToInt16(Coll["MailR"]);
                        model.FreeBees = Convert.ToInt16(Coll["FreeBees"]);
                        model.PortletFile = Coll["PortletName"].ToString();
                        //model.CreatedBy = Convert.ToInt32(HttpContext.Session.GetString("UserId"));//Convert.ToInt16(Session["UserId"]);
                        intOut = _functionService.AddFunction(model);
                        ViewData["result"] = intOut;
                        ModelState.Clear();
                        //return View("AddFunctionMaster");
                        return RedirectToAction("ViewFunctionMasterActive", new { Status = "Sucessfully Added " });
                    }
                    else
                    {
                        return View();
                    }
                }
                catch (Exception)
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("AddFunctionMaster");
            }

        }
        #endregion
        #region View Active Function Master
        //[AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ViewFunctionMasterActive(IFormCollection Coll, int? pages, string Status)
        {
            //this.Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            //this.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            //this.Response.Cache.SetNoStore();
            //if (Session["UserId"] == null)
            //{
            //    return RedirectToAction("Default", "Login");
            //}
            ViewData["result"] = Status;
            FunctionMasterModel model = new FunctionMasterModel();
            model.FunctionName = Coll["fn"];
            string Funname = model.FunctionName;
            var pageNumber = pages ?? 1;
            model.ActionCode = "V";
            model.Flag = 1;
            if (model.FunctionName == "" || model.FunctionName == null)
            {
                model.FunctionName = string.Empty;
            }
            else
            {
                model.ActionCode = "V";
            }
            var Strmodel = _functionService.GetAllFunction(model).ToPagedList(pageNumber, defaultPageSize);
            ViewData["Funname"] = Funname;
            ViewBag.Strmodel = Strmodel;
            return View(Strmodel);

        }
        #endregion
        #region View Inactive Function Master
        //[AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ViewFunctionMasterInActive(IFormCollection Coll, int? page)
        {
            FunctionMasterModel model = new FunctionMasterModel();
            model.ActionCode = "V";
            model.FunctionName = Coll["fn"];
            string Funname = model.FunctionName;
            model.Flag = 0;
            var posts = _functionService.GetAllFunction(model);
            var pageNumber = page ?? 1;
            if (model.FunctionName == "" || model.FunctionName == null)
            {
                model.FunctionName = "";
            }

            var Strmodel = _functionService.GetAllFunction(model).ToPagedList(pageNumber, defaultPageSize); ;//.ToPagedList(pageNumber, defaultPageSize);
            ViewData["Funname"] = Funname;
            ViewBag.Strmodel = Strmodel;
            return View(Strmodel);


        }
        #endregion
        #region InActive Function Master
        //[HttpPost]
        public ActionResult InActiveFunctionMaster(params string[] checkResp)
        {
            try
            {
                foreach (string Id in checkResp)
                {
                    FunctionMasterModel model = new FunctionMasterModel();
                    model.ActionCode = "I";
                    // string strPids = string.Join(",", checkResp);
                    model.FunctionId = Id;
                    model.CreatedBy = 1; // Convert.ToInt16(Session["UserId"]);
                    intOut = _functionService.ActiveFunction(model);
                }
                //    FunctionMaster model = new FunctionMaster();
                //model.ActionCode = "I";
                //string strPids = string.Join(",", checkResp);
                //model.FunctionId = strPids;
                //model.CreatedBy = 1; // Convert.ToInt16(Session["UserId"]);
                //intOut = _functionService.ActiveFunction(model);

                return RedirectToAction("ViewFunctionMasterActive");

            }
            catch
            {
                return View();
            }
        }
     
        #endregion
        #region Active Function Master
        //[HttpPost]
        public ActionResult ActiveFunctionMaster(params string[] checkResp)
        {
            try
            {
                foreach (string Id in checkResp)
                {
                    FunctionMasterModel model = new FunctionMasterModel();
                    model.ActionCode = "T";
                    model.FunctionId = Id;
                    model.CreatedBy = 1;
                    intOut = _functionService.ActiveFunction(model);
                }
                //FunctionMaster model = new FunctionMaster();
                //model.ActionCode = "T";
                //string strPids = string.Join(",", checkResp);
                //model.FunctionId = strPids;
                //model.CreatedBy = 1;// Convert.ToInt16(Session["UserId"]);
                //intOut = _functionService.ActiveFunction(model);
                return RedirectToAction("ViewFunctionMasterInActive");
            }
            catch (Exception)
            {
                return View();
            }
        }
      
        #endregion

        public ActionResult EditActiveFunction(string id)
        {
            try
            {
                id = (CommonFunction.Decrypt(id));
                FunctionMasterModel model = new FunctionMasterModel();
                model.ActionCode = "E";
                model.FunctionId = id;
                model.Flag = 1;
                IList<FunctionMasterModel> objFunList = new List<FunctionMasterModel>();
                objFunList = _functionService.GetAllFunction(model);
                foreach (var i in objFunList)
                {
                    ObjFun.FunctionName = i.FunctionName;
                    ObjFun.FileName = i.FileName;
                    ViewData["Description"] = i.Description;
                    ViewData["DescriptionLen"] = 500 - Convert.ToInt16(i.Description.Length);
                    if (i.FAdd == "Y")
                        ViewData["FAdd"] = true;
                    else
                        ViewData["FAdd"] = false;
                    if (i.FView == "Y")
                        ViewData["FView"] = true;
                    else
                        ViewData["FView"] = false;
                    if (i.FManage == "Y")
                        ViewData["FManage"] = true;
                    else
                        ViewData["FManage"] = false;
                    ObjFun.MailR = i.MailR;
                    ObjFun.FreeBees = i.FreeBees;
                    ObjFun.PortletFile = i.PortletFile;
                }
                return View(ObjFun);

            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult EditActiveFunction(string id, IFormCollection Coll, string Command)
        {
            if (Command == "Update")
            {

ClaimBaseTest.Web/Views/FunctionMaster/EditActiveFunction.cshtml
@model CodeGen.Model.FunctionMasterModel.FunctionMasterModel

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "EditActiveFunction";

}

<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Edit Function Master</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Manage Master</li>
                    <li class="breadcrumb-item active" aria-current="page">Function Master</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link active" asp-controller="FunctionMaster" asp-action="AddFunctionMaster">Add</a>
                        <a class="nav-item nav-link" asp-controller="FunctionMaster" asp-action="ViewFunctionMasterActive">Active</a>
                        <a class="nav-item nav-link" asp-controller="FunctionMaster" asp-action="ViewFunctionMasterInActive">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>



                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Function Name <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.TextBoxFor(model => model.FunctionName, new { @class = "form-control", maxlength = 150, autofocus = "true", Onkeypress = "return inputLimiter(event,'NameCharactersymbol')" })
                                @Html.ValidationMessageFor(model => model.FunctionName)
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"> File Name <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.TextBoxFor(model => model.FileName, new { @class = "form-control", maxlength = 150, Onkeypress = "return inputLimiter(event,'Filename')" })
                                @Html.ValidationMessageFor(model => model.FileName)

                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Description <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.TextArea("Description", (string)ViewData["Description"], new { @class = "form-control", maxlength = 98, Onkeypress = "return inputLimiter(event,'Description')" })
                                @Html.ValidationMessageFor(model => model.Description)<span class="mandatory">*</span>
                                Maximum <span class="mandatory" id="SpanLbl">
                                    @ViewData["DescriptionLen"]
                                </span>Character Allowed

                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Permission <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.CheckBox("CheckBoxAdd", (bool)ViewData["FAdd"])<span> Add </span>
                                @Html.CheckBox("CheckBoxView", (bool)ViewData["FView"])<span> View </span>
                                @Html.CheckBox("CheckBoxManage", (bool)ViewData["FManage"])<span> Manage </span>

                            </div>
                        </div>
                        <div class="form-group row" style="display:none">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">External Mail Required <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.RadioButtonFor(model => model.MailR, "1") Yes @Html.RadioButtonFor(model => model.MailR, "0")
                                No <span class="mandatory">@Html.ValidationMessageFor(model => model.MailR)</span>

                            </div>
                        </div>
                        <div class="form-group row" style="display:none">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Freebees <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.RadioButtonFor(model => model.FreeBees, "1") Yes
                                @Html.RadioButtonFor(model => model.FreeBees, "0")
                                No <span class="mandatory">@Html.ValidationMessageFor(model => model.FreeBees)</span>
                            </div>
                        </div>
                        <div class="form-group row" style="display:none">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Portlet File Name <span class="text-danger">*</span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                @Html.TextBoxFor(model => model.PortletFile, new { @class = "form-control", maxlength = 150, Onkeypress = "return inputLimiter(event,'Filename')" })
                                @Html.ValidationMessageFor(model => model.PortletFile)
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon"></span>
                                <input type="submit" value="Update" class="btn btn-success btn-sm" id="btn1" name="Command" />
                                <input type="submit" value="Cancel" class="btn btn-success btn-danger" id="btn2" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {

    <script type="text/javascript" src="@Url.Content("~/admjs/validator.js")"></script>
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {

            window.history.forward();  //Disable back button after logout
            $('#CheckBoxAdd').prop('checked')

            $('#Description').keyup(function () {
                var left = 500 - $(this).val().length;
                if (left < 0) {
                    left = 0;
                }
                $('#SpanLbl').text(left);
            });

            $("#btn2").click(function (event) {
                event.preventDefault();
                var url = '@Url.Action("ViewFunctionMasterActive", "FunctionMaster")';
                window.location.href = url;
            });
        });
    </script>
    <script type="text/javascript" language="javascript">
        $(function () {

            $("#btn1").click(function () {
                if (!blankFieldValidation('FunctionName', 'Function Name')) {
                    return false;
                }
                if (!WhiteSpaceValidation1st('FunctionName', 'Function Name')) {
                    return false;
                }
                if (!blankFieldValidation('FileName', 'File Name')) {
                    return false;
                }
                if (!WhiteSpaceValidation1st('FileName', 'File Name')) {
                    return false;
                }
                if (!blankFieldValidation('Description', 'Description')) {
                    return false;
                }
                if (!WhiteSpaceValidation1st('Description', 'Description')) {
                    return false;
                }
                if ((document.getElementById('CheckBoxAdd').checked == false) && (document.getElementById('CheckBoxView').checked == false) && (document.getElementById('CheckBoxManage').checked == false)) {
                    alert('Please choose Permission');
                    $("#Add").focus();
                    return false;
                }
                //                if (!WhiteSpaceValidation1st('PortletName', 'Portlet Name')) {
                //                    return false;
                //                }
                //                if (!blankFieldValidation('PortletName', 'Portlet Name')) {
                //                    return false;
                //                }
                if (confirm("Are you sure you want to Update this?")) {
                    return true;
                } else {
                    return false;
                }

            });
        });
    </script>
    <script type="text/javascript">
        function inputLimiter(e, allow) {
            var AllowableCharacters = '';

            if (allow == 'NameCharactersymbol') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz./&';
            }
            if (allow == 'NameCharacters') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.\'';
            }
            if (allow == 'NameCharactersAndNumbers') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-,/.\'';
            }
            if (allow == 'Description') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.,()/';
            }
            if (allow == 'Numbers') {
                AllowableCharacters = '1234567890';
            }
            if (allow == 'Decimal') {
                AllowableCharacters = '1234567890.';
            }
            if (allow == 'Filename') {
                AllowableCharacters = '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz/';
            }
            var k;
            k = document.all ? parseInt(e.keyCode) : parseInt(e.which);
            if (k != 13 && k != 8 && k != 0) {
                if ((e.ctrlKey == false) && (e.altKey == false)) {
                    return (AllowableCharacters.indexOf(String.fromCharCode(k)) != -1);
                }
                else {
                    return true;
                }
            }
            else {
                return true;
            }
        }
    </script>


}

@{
    if (ViewData["result"] != null)
    {
        ViewData["result"] = null;
        <script type="text/javascript" language="javascript">
            alert("Function updated Successfully");
        </script>
    }

}
@{
    if (ViewData["result1"] != null)
    {
        ViewData["result1"] = null;
        <script type="text/javascript" language="javascript">
            alert("Function already exists");
        </script>
    }

}