ClaimBaseTest.Web/Controllers/AdminConsole_Controllers/LevelMasterController.cs
using CodeGen.Model.LevelMasterModel;
using CodeGen.Repository.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace ClaimBaseTest.Web
{
    public class LevelMasterController : Controller
    {



        public readonly  IHierarchyServiceProviderRepository  _hirerarchyServiceProvider ;
        public readonly ILevelServiceProvider _levelServiceProvider ;
       CreateLevelMaster model = new CreateLevelMaster();

        public LevelMasterController(IHierarchyServiceProviderRepository hirerarchyServiceProvider,ILevelServiceProvider levelServiceProvider)
        {
            _hirerarchyServiceProvider = hirerarchyServiceProvider;
            _levelServiceProvider=levelServiceProvider;
        }
        [HttpGet]
        public async Task<IActionResult> AddLevelMaster(string Status)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{

                model.HierarchyList = (await _hirerarchyServiceProvider.GetAllHierarchy(1)).HierarchyList.ToList();
               // model.INTCREATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                return View(model);
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}

        }
        [HttpGet]
        public async Task<JsonResult> BindParentLevelByHierarchyId(int HId)
        {
            var result = (await _levelServiceProvider.GetAllLevelByHierarchyId(HId)).ParentLevelList.ToList();
            return Json(result);
        }
        #region Add  Level
        [HttpPost]
        public IActionResult AddLevelMaster(CreateLevelMaster objlevel)
        {
            try
            {
                var Result = _levelServiceProvider.AddLevel(objlevel);
                //return RedirectToAction("ViewActiveLevel", new { Status = "success"  });
                return RedirectToAction("ViewActiveLevel", new { Status = "Added Successfully." });

                //if (Result == "Save Successfully")
                //{
                //    return RedirectToAction("ViewActiveLevel", new { Status = "Record " + Result });

                //}
                //else

                //{
                //    model.HierarchyList = (await _hirerarchyServiceProvider.GetAllHierarchy(1)).HierarchyList.ToList();
                //    model.INTPARENTID = objlevel.INTPARENTID;
                //    TempData["CommandStatus"] = "Record " + Result;
                //    return View(model);
                //}

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        #endregion
        #region view  Level data
        [HttpGet]
        public async Task<IActionResult> ViewActiveLevel(string Status)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                try
                {
                    LevelMasterModel vmodel = new LevelMasterModel();
                    vmodel.LevelList = (await _levelServiceProvider.GetAllLevel(1)).LevelList.ToList();
                    TempData["CommandStatus"] = Status;
                    return View(vmodel);

                }
                catch (Exception ex)
                {

                    throw ex;
               }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}



        }
        [HttpGet]
        public async Task<IActionResult> ViewInActiveLevel(string Status)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                try
                {
                    LevelMasterModel vmodel = new LevelMasterModel();
                    vmodel.LevelList = (await _levelServiceProvider.GetAllLevel(0)).LevelList.ToList();
                    TempData["CommandStatus"] = Status;
                    return View(vmodel);

                }
                catch (Exception ex)
                {

                    throw ex;
                }

            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}


        }
        #endregion
        #region Get  Level by Id
        public async Task<IActionResult> EditActiveLevel(int id)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                try
                {
                    model.HierarchyList = (await _hirerarchyServiceProvider.GetAllHierarchy(1)).HierarchyList.ToList();
                    var result = _levelServiceProvider.GetLevelById(id).Result;
                    model.INTHIERARCHYID = result.ToList()[0].INTHIERARCHYID;
                    model.INTLEVELID = result.ToList()[0].INTLEVELID;
                    model.INTPARENTID = result.ToList()[0].INTPARENTID;
                    model.NVCHLABEL = result.ToList()[0].NVCHLABEL;
                    model.VCHALLIAS = result.ToList()[0].VCHALLIAS;
                   // model.INTUPDATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                    return View(model);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}
        }
        #endregion
        #region Update Level
        [HttpPost]
        public IActionResult EditLevel(CreateLevelMaster objlevel)
        {
            try
            {

                var Result = _levelServiceProvider.EditLevel(objlevel);
                //return RedirectToAction("ViewActiveLevel", new { Status = "Record " + Result });
                return RedirectToAction("ViewActiveLevel", new { Status = "Updated Successfully." });

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion
        #region Mark As Inactive
        [HttpPost]
        public IActionResult MarkAsInactive(string[] chkbox)
        {
            try
            {
                LevelMasterModel vmodel = new LevelMasterModel();
                string LevelId = string.Join(",", chkbox);
                var Result = String.Empty;
                //vmodel.INTUPDATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                foreach (string Id in chkbox)
                {
                    vmodel.INTLEVELID = Id;

                    Result = _levelServiceProvider.MarkInactive(vmodel);
                }
                return RedirectToAction("ViewActiveLevel", new { Status = "Record " + Result });

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion
        #region Mark As Active
        [HttpPost]
        public IActionResult MarkAsActive(string[] chkbox)
        {
            try
            {

                LevelMasterModel vmodel = new LevelMasterModel();
               // vmodel.INTUPDATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                var Result = String.Empty;
                foreach (string Id in chkbox)
                {
                    vmodel.INTLEVELID = Id;
                    Result = _levelServiceProvider.MarkActive(vmodel);
                }
                return RedirectToAction("ViewActiveLevel", new { Status = "Record " + Result });

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion
    }
    
 }

ClaimBaseTest.Web/Views/LevelMaster/AddLevelMaster.cshtml
@model CodeGen.Model.LevelMasterModel.CreateLevelMaster
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewData["Title"] = "AddLevelMaster";

}




@section Scripts {
    @*<script type="text/javascript"
            src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>*@
    <script src="~/js/AdminConsole/HierarchyMaster.js"></script>
    @*$(document).ready(function () {
    @if (TempData["CommandStatus"] != null)
    {
        <script type="text/javascript">
        alert('@(TempData["CommandStatus"])');
        $("#txtLevelName").focus();
        </script>
    }
    });*@
    <script>
        $(document).ready(function () {
           // BindupdateParentLevel();
            BindParentLevel();
             $('#dvparentLevel').hide();
            
        });
    </script>

    <script>
        function BindParentLevel() {
            var HirerarchyId = $('#ddlHierarchy').val();
            var data = {
                HId: HirerarchyId

            };

            $.ajax({
                type: 'GET',
                  url: '@Url.Content("~/LevelMaster/BindParentLevelByHierarchyId")',
               // url: '/LevelMaster/BindParentLevelByHierarchyId',
                data: data,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    //console.log(response.length);
                   // alert(response.length);
                     var dvparentLeveldisplay = document.getElementById("dvparentLevel");
                    if (response.length == 0) {
                        $('#dvparentLevel').hide();
                        //dvparentLeveldisplay.style.display = "none";
                     
                    } else
                    {
                         $('#dvparentLevel').show();
                        // dvparentLeveldisplay.style.display = "block";
                         $("#hdnparentid").val(response.length);
                    // alert(document.getElementById("hdnparentid").value);
                    // console.log(response);
                    $("#ddlparentlevelId").empty();
                    $("#ddlparentlevelId").append($('<option value="0">--Select Parent Level--</option>'));
                    if (response.length > 0) {
                        for (var i = 0; i < response.length; i++) {
                            $("#ddlparentlevelId").append($('<option/>')
                                .val(response[i].intlevelid)
                                .html(response[i].nvchlabel)
                            );
                        }
                          $('#ddlparentlevelId').val(@Model.INTPARENTID);
                    }

                    }
                   


                },
                error: function (error) {
                    console.log(error);
                }
            });
            return true;


        }
          function BindupdateParentLevel() {
            var HirerarchyId = $('#ddlHierarchy').val();
            var data = {
                HId: HirerarchyId

            };

            $.ajax({
                type: 'GET',
                   url: '@Url.Content("~/LevelMaster/BindParentLevelByHierarchyId")',
               // url: '/LevelMaster/BindParentLevelByHierarchyId',
                data: data,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#hdnparentid").val(response.length);
                    $("#ddlparentlevelId").empty();
                    $("#ddlparentlevelId").append($('<option value="0">--Select Parent Level--</option>'));
                    if (response.length > 0) {
                        for (var i = 0; i < response.length; i++) {
                            $("#ddlparentlevelId").append($('<option/>')
                                .val(response[i].intlevelid)
                                .html(response[i].nvchlabel)
                            );
                             $('#ddlparentlevelId').val(@Model.INTPARENTID);
                        }
                    }



                },
                error: function (error) {
                    console.log(error);
                }
            });
            return true;


        }
    </script>

    <script type="text/javascript" language="javascript">
        function validateForm() {
            var x = document.forms["frmCreateLevelMaster"]["NVCHLABEL"].value;
            if ($("#ddlHierarchy").val() == 0) {
                $("#ddlHierarchy").focus();
                alert("Please Select Hierarchy Name.");
                return false;
            }
            else if ($("#txtLevelName").val() == "") {
                $("#txtLevelName").focus();
                alert(" Level Name Can't be blank.");
                return false;
            }
            else if ($("#txtLeveldetailName").val() == "") {
                $("#txtLeveldetailName").focus();
                alert("Alias Name Can't be blank.");
                return false;
            }
            //else if ($("#hdnparentid").val() > 0) {
            //        if ($("#ddlparentlevelId").val() == 0) {
            //            $("#ddlparentlevelId").focus();
            //            alert("Please Select parent level.");
            //            return false;
            //        }

            //}

            else {
                return confirm('Are you sure you want to  create this?');
            }
        }


        function inputLimiter(e, allow) {
            var AllowableCharacters = '';

            if (allow == 'NameCharactersymbol') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz./&';
            }
            if (allow == 'NameCharacters') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.\'';
            }
            if (allow == 'Email') {
                AllowableCharacters = '1234567890@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_.';
            }
            if (allow == 'Description') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.,()/';
            }
            if (allow == 'NameCharactersAndNumbers') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-,/.\'';
            }
            if (allow == 'Numbers') {
                AllowableCharacters = '1234567890';
            }
            if (allow == 'Decimal') {
                AllowableCharacters = '1234567890.';
            }
            if (allow == 'Filename') {
                AllowableCharacters = '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz/';
            }
            var k;
            k = document.all ? parseInt(e.keyCode) : parseInt(e.which);
            if (k != 13 && k != 8 && k != 0) {
                if ((e.ctrlKey == false) && (e.altKey == false)) {
                    return (AllowableCharacters.indexOf(String.fromCharCode(k)) != -1);
                }
                else {
                    return true;
                }
            }
            else {
                return true;
            }
        }

    </script>
    <script type="text/javascript">
        $(function () {
            $("#btnReset").bind("click", function () {
                $("#ddlHierarchy")[0].selectedIndex = 0;
                $("#ddlparentlevelId")[0].selectedIndex = 0;
                document.forms["frmCreateLevelMaster"]["NVCHLABEL"].value = "";
            });
        });
    </script>




}
<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Add Level Master</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Level Master</li>
                    <li class="breadcrumb-item active" aria-current="page">Add Level Master</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link active" asp-controller="LevelMaster" asp-action="AddLevelMaster">Add</a>
                        <a class="nav-item nav-link" asp-controller="LevelMaster" asp-action="ViewActiveLevel">Active</a>
                        <a class="nav-item nav-link" asp-controller="LevelMaster" asp-action="ViewInActiveLevel">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>
                <div class="card-body">
                    <form id="frmCreateLevelMaster" data-parsley-validate novalidate method="post" asp-action="AddLevelMaster" asp-controller="LevelMaster" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Hirerarchy Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <select asp-for="INTHIERARCHYID" asp-items="@(new SelectList(Model.HierarchyList,"INTHIERARCHYID","NVCHHIERARCHYNAME"))" onchange=" return BindParentLevel();" id="ddlHierarchy" class="form-control" autofocus>
                                    <option value="0">--Select Hirerarchy Name--</option>
                                </select>
                            </div>

                        </div>
                        <div class="form-group row" id="dvparentLevel">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Parent Level
                                <span class="text-danger"></span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <select asp-for="INTPARENTID" id="ddlparentlevelId" class="form-control">
                                </select>
                            </div>

                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Level Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="NVCHLABEL" id="txtLevelName" style="text-transform:uppercase" Onkeypress="return inputLimiter(event,'NameCharactersymbol')" class="form-control" placeholder="Enter Level Name" autocomplete="off" maxlength="100" />
                                <input asp-for="INTCREATEDBY" type="hidden" value=@Model.INTCREATEDBY />
                                <input type="hidden" id="hdnparentid" />
                            </div>


                        </div>

                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Alias Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="VCHALLIAS" id="txtLeveldetailName" style="text-transform:uppercase" Onkeypress="return inputLimiter(event,'NameCharactersymbol')" class="form-control" placeholder="Enter Level Name" autocomplete="off" maxlength="100" />
                                <input asp-for="INTCREATEDBY" type="hidden" value=@Model.INTCREATEDBY />
                                <input type="hidden" id="hdnparentid" />
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"> <span class="text-danger"></span></label>

                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon"></span>
                                <button type="submit" name="submit" id="btnsubmit" class="btn btn-primary mb-1t white-text" title="Submit" value="Submit">Submit</button>
                                <input type="button" id="btnReset" value="Reset" class="btn btn-danger" title="Reset" />
                            </div>
                        </div>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>

ClaimBaseTest.Web/Views/LevelMaster/ViewActiveLevel.cshtml
@model CodeGen.Model.LevelMasterModel.LevelMasterModel
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewData["Title"] = "Active Global Link";
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#example1').DataTable();
        });
    </script>
    <script>
        function check_uncheck_checkbox(isChecked) {
            if (isChecked) {
                $('input[name="chkbox"]').each(function () {
                    this.checked = true;
                });
            }
            else {
                $('input[name="chkbox"]').each(function () {
                    this.checked = false;
                });
            }
        }
        function ClearField() {
            $('input[type=checkbox]').prop('checked', false);
        }

    </script>
    <script type="text/javascript" language="javascript">
        function validateForm() {
            if ($('#example1 :checked').length == 0) {
                alert("No record selected for Inactive!");
                return false;
            }
            else {
                return confirm('Are you sure you want to Mark As In-Active?');
            }
        }


    </script>

}
    @{
    if (TempData["CommandStatus"] != null)
    {
        <script type="text/javascript">
            alert('@(TempData["CommandStatus"])');
        </script>
    }

}

<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Active Level Master</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Level Master</li>
                    <li class="breadcrumb-item active" aria-current="page">Active Level Master</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link" asp-controller="LevelMaster" asp-action="AddLevelMaster">Add</a>
                        <a class="nav-item nav-link active" asp-controller="LevelMaster" asp-action="ViewActiveLevel">Active</a>
                        <a class="nav-item nav-link" asp-controller="LevelMaster" asp-action="ViewInActiveLevel">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>
                <div class="card-body">
                    @if (Model.LevelList.Count != 0)
                    {
                        <form id="frmActive" data-parsley-validate novalidate method="post" asp-action="MarkAsInactive"
                          asp-controller="LevelMaster" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                            <div class="table-responsive">
                                <table data-toggle="table" class="table table-hover table-bordered table-padding" id="example1">

                                    <thead>
                                        <tr>
                                            <th width="10px"><input type="checkbox" id="checkBoxAll" onclick="check_uncheck_checkbox(this.checked)" /></th>
                                            <th width="10px">SL#</th>
                                            <th width="100px">Hierarchy Name</th>
                                            <th width="100px">Parent Level Name</th>
                                            <th width="20px">Level Name</th>
                                            <th width="20px">Alias Name</th>
                                            <th width="20px">Edit</th>


                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.LevelList.Count != 0)
                                        {
                                            @foreach (var level in Model.LevelList.Select((x, i) => new { Data = x, Index = i + 1 }))
                                            {

                                                <tr>
                                                    <td><input type="checkbox" name="chkbox" value="@level.Data.INTLEVELID" /></td>
                                                    <td>@level.Index</td>
                                                    <td>@Html.DisplayFor(modelItem => level.Data.NVCHHIERARCHYNAME)</td>
                                                    <td>@Html.DisplayFor(modelItem => level.Data.parentlevel)</td>
                                                    <td>@Html.DisplayFor(modelItem => level.Data.NVCHLABEL)</td>
                                                    <td>@Html.DisplayFor(modelItem => level.Data.VCHALLIAS)</td>
                                                    <td>
                                                        <a class="btn btn-info btn-sm" data-toggle="tooltip" data-original-title="Edit" asp-controller="LevelMaster" asp-action="EditActiveLevel" asp-route-id="@level.Data.INTLEVELID">
                                                            <i class="icon-edit1">Edit</i>
                                                        </a>
                                                    </td>

                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr style="text-align: center;font-size: x-large;font-weight: bolder;">
                                                <td colspan='6' align='center'> No records found!</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>


                                <button type="submit" name="submitButton" class="btn btn-primary mb-1t white-text" title="Mark AS Inactive" value="submit">Mark AS Inactive</button>
                                <button type="button" title="Reset" class="btn btn-danger" onclick="return ClearField();"><span>Reset</span></button>
                            </div>
                        </form>
                    }
                    else

                    {

                        <h4>Record Not Found</h4>
                    }

                    <div class="table-responsive">
                    </div>
                </div>



            </div>

        </div>

    </div>
</div>