ClaimBaseTest.Web/Controllers/AdminConsole_Controllers/ProjectLinkController.cs
using CodeGen.Model.ProjectMaster;
using CodeGen.Repository.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace ClaimBaseTest.Web
{
    public class ProjectLinkController : Controller
    {



        private readonly IProjectLinkServiceProvider _projectLinkService;
        Project model = new Project();

        public ProjectLinkController(IProjectLinkServiceProvider projectLinkService)
        {
            _projectLinkService = projectLinkService;
        }
        [HttpGet]
        public async Task<IActionResult> AddProjectLink(string Status)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{

                TempData["CommandStatus"] = Status;
                //ViewBag.CREATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));

                return View();
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}

        }
      
        [HttpPost]
        public IActionResult AddProjectLink(Project objproject)
        {
            try
            {
                var Result = _projectLinkService.AddProjectLink(objproject);
                return RedirectToAction("ViewActiveProjectLink", new { Status = "Record " + Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
        public IActionResult UpdateProjectLink(Project objproject)
        {
            try
            {
                var Result = _projectLinkService.UpdateProjectLink(objproject);
                return RedirectToAction("ViewActiveProjectLink", new { Status = "Record " + Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #region view  ProjectLink
        [HttpGet]
        public async Task<IActionResult> ViewActiveProjectLink(string Status)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{

                try
                {
                    ViewProjectLink vmodel = new ViewProjectLink();
                    vmodel.ViewProjectLinkDetailsmodel = (await _projectLinkService.GetAllActiveProjectLink()).ViewProjectLinkDetailsmodel.ToList();
                    TempData["CommandStatus"] = Status;
                    return View(vmodel);
                }
                catch (Exception ex)
                {

                    throw ex;
                }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}



        }
        [HttpGet]
        public async Task<IActionResult> ViewInActiveProjectLink(string Status)
        {
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                try
                {
                    ViewProjectLink vmodel = new ViewProjectLink();
                    vmodel.ViewProjectLinkDetailsmodel = (await _projectLinkService.GetAllInActiveProjectLink()).ViewProjectLinkDetailsmodel.ToList();
                    TempData["CommandStatus"] = Status;
                    return View(vmodel);

                }
                catch (Exception ex)
                {

                    throw ex;
                }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}




        }
        #endregion
        #region Mark As InActive/Active Project Link
        [HttpPost]
        public IActionResult MarkAsInActive(string[] chkbox, int updatedby)
        {
            try
            {
                string primarylinkId = string.Join(",", chkbox);
                var Result = String.Empty;
                foreach (string Id in chkbox)
                {
                    Result = _projectLinkService.InactiveProjectLink(Convert.ToInt32(Id), Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                }
                return RedirectToAction("ViewActiveProjectLink", new { Status = Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
        public IActionResult MarkActive(string[] chkbox, int updatedby)
        {
            try
            {
                string primarylinkId = string.Join(",", chkbox);
                var Result = String.Empty;
                foreach (string Id in chkbox)
                {
                    Result = _projectLinkService.ActiveProjectLink(Convert.ToInt32(Id), Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                }
                return RedirectToAction("ViewActiveProjectLink", new { Status = Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
      
        #endregion
        public async Task<IActionResult> EditActiveProjectLink(int id)
        {

            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                ViewProjectLink model = new ViewProjectLink();
                try
                {
                    model.ProjectLinkModelIdwise = (await _projectLinkService.GetById(id)).ProjectLinkModelIdwise.ToList();

                    Project m = new Project();
                    m.INTPROJECTLINKID = model.ProjectLinkModelIdwise[0].INTPROJECTLINKID; ;
                    m.NVCHPROJECTLINKNAME = model.ProjectLinkModelIdwise[0].NVCHPROJECTLINKNAME;
                    m.NVCHPROJECTLINKDESC = model.ProjectLinkModelIdwise[0].NVCHPROJECTLINKDESC;
                    //m.INTUPDATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                    return View(m);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}
        }
}
}

ClaimBaseTest.Web/Views/ProjectLink/AddProjectLink.cshtml
@model CodeGen.Model.ProjectMaster.Project
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Add Project Link";
}


@section Scripts {
    <script type="text/javascript" language="javascript">
        function validateForm() {
            if ($("#txtprojectname").val() == "") {
                $("#txtprojectname").focus();
                alert(" Project Link Name Can't be blank.");
                return false;

            }

            else {
                return confirm('Are you sure you want to  create this?');
            }
        }

        function inputLimiter(e, allow) {
            var AllowableCharacters = '';

            if (allow == 'NameCharactersymbol') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz./&';
            }
            if (allow == 'NameCharacters') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.\'';
            }
            if (allow == 'Email') {
                AllowableCharacters = '1234567890@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_.';
            }
            if (allow == 'Description') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.,()/';
            }
            if (allow == 'NameCharactersAndNumbers') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-,/.\&';
            }
            if (allow == 'Numbers') {
                AllowableCharacters = '1234567890';
            }
            if (allow == 'Decimal') {
                AllowableCharacters = '1234567890.';
            }
            if (allow == 'Filename') {
                AllowableCharacters = '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz/';
            }
            var k;
            k = document.all ? parseInt(e.keyCode) : parseInt(e.which);
            if (k != 13 && k != 8 && k != 0) {
                if ((e.ctrlKey == false) && (e.altKey == false)) {
                    return (AllowableCharacters.indexOf(String.fromCharCode(k)) != -1);
                }
                else {
                    return true;
                }
            }
            else {
                return true;
            }
        }
        function ClearField() {
                $('#txtprojectname').val('');
                $('#txtprojectdesc').val('');
                }
       
    </script>

}
<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Add Project Link</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Project Link</li>
                    <li class="breadcrumb-item active" aria-current="page">Add Project Link</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">

                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link active" asp-controller="ProjectLink" asp-action="AddProjectLink">Add</a>
                        <a class="nav-item nav-link" asp-controller="ProjectLink" asp-action="ViewActiveProjectLink">Active</a>
                        <a class="nav-item nav-link" asp-controller="ProjectLink" asp-action="ViewInActiveProjectLink">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>
                <div class="card-body">
                    <form id="frmCreateProject" data-parsley-validate novalidate method="post" asp-action="AddProjectLink" asp-controller="ProjectLink" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Project Link Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>

                                <input asp-for="NVCHPROJECTLINKNAME" type="text" id="txtprojectname" name="NVCHPROJECTLINKNAME"
                                       class="form-control" Onkeypress="return inputLimiter(event,'NameCharactersAndNumbers')"
                                       placeholder="Enter Project Link Name" autocomplete="off" maxlength="50" autofocus />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Project Link Description
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <textarea asp-for="NVCHPROJECTLINKDESC" type="text" id="txtprojectdesc" name="NVCHPROJECTLINKDESC" Onkeypress="return inputLimiter(event,'Description')" class="form-control" placeholder="EnterProject  Description" autocomplete="off" maxlength="200">

                </textarea>
                            </div>


                            <input asp-for="INTCREATEDBY" type="hidden" value='@ViewBag.CREATEDBY' />
                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"> <span class="text-danger"></span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon"></span>
                                <button type="submit" name="submit" id="btnsubmit" class="btn btn-primary mb-1t white-text" title="Submit" value="Submit">Submit</button>
                                <button type="button" class="btn btn-danger" title="Reset" onclick="return ClearField();"> Reset </button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>

ClaimBaseTest.Web/Views/ProjectLink/EditActiveProjectLink.cshtml
@model CodeGen.Model.ProjectMaster.Project
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Add Project Link";
}


@section Scripts {
    <script type="text/javascript" language="javascript">
        function validateForm() {
            if ($("#txtprojectname").val() == "") {
                $("#txtprojectname").focus();
                alert(" Project Link Name Can't be blank.");
                return false;

            }

            else {
                return confirm('Are you sure you want to  update this?');
            }
        }

        function inputLimiter(e, allow) {
            var AllowableCharacters = '';

            if (allow == 'NameCharactersymbol') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz./&';
            }
            if (allow == 'NameCharacters') {
                AllowableCharacters = ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.\'';
            }
            if (allow == 'Email') {
                AllowableCharacters = '1234567890@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_.';
            }
            if (allow == 'Description') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-.,()/';
            }
            if (allow == 'NameCharactersAndNumbers') {
                AllowableCharacters = '1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-,/.\&';
            }
            if (allow == 'Numbers') {
                AllowableCharacters = '1234567890';
            }
            if (allow == 'Decimal') {
                AllowableCharacters = '1234567890.';
            }
            if (allow == 'Filename') {
                AllowableCharacters = '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz/';
            }
            var k;
            k = document.all ? parseInt(e.keyCode) : parseInt(e.which);
            if (k != 13 && k != 8 && k != 0) {
                if ((e.ctrlKey == false) && (e.altKey == false)) {
                    return (AllowableCharacters.indexOf(String.fromCharCode(k)) != -1);
                }
                else {
                    return true;
                }
            }
            else {
                return true;
            }
        }

         $(function () {
            $("#btnReset").bind("click", function () {
                  var url = '@Url.Action("ViewActiveProjectLink", "ProjectLink")';
                window.location.href = url;

            });
        });
    </script>

    

}
<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Add Project Link</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Project Link</li>
                    <li class="breadcrumb-item active" aria-current="page">Add Project Link</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">

                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link " asp-controller="ProjectLink" asp-action="AddProjectLink">Add</a>
                        <a class="nav-item nav-link active" asp-controller="ProjectLink" asp-action="ViewActiveProjectLink">Active</a>
                        <a class="nav-item nav-link" asp-controller="ProjectLink" asp-action="ViewInActiveProjectLink">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>
                <div class="card-body">
                    <form id="frmCreateHierarchy" data-parsley-validate novalidate method="post" asp-action="UpdateProjectLink" asp-controller="ProjectLink" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Project Link Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>

                                <input asp-for="NVCHPROJECTLINKNAME" type="text" id="txtprojectname" name="NVCHPROJECTLINKNAME"
                                       class="form-control" Onkeypress="return inputLimiter(event,'NameCharactersAndNumbers')"
                                       placeholder="Enter Project Link Name" autocomplete="off" maxlength="50" autofocus />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Project Link Description
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <textarea asp-for="NVCHPROJECTLINKDESC" type="text" id="txtprojectdesc" name="NVCHPROJECTLINKDESC" Onkeypress="return inputLimiter(event,'Description')" class="form-control" placeholder="EnterProject  Description" autocomplete="off" maxlength="200">
                             </textarea>
                            </div>
                            <input asp-for="INTPROJECTLINKID" type="hidden" value=@Model.INTPROJECTLINKID />
                            <input asp-for="INTUPDATEDBY" type="hidden" value=@Model.INTUPDATEDBY />
                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"> <span class="text-danger"></span></label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon"></span>
                                <button type="submit" name="submit" id="btnsubmit" class="btn btn-primary mb-1t white-text" title="Submit" value="Submit">Update</button>
                                <button type="button" class="btn btn-danger" title="Reset" id="btnReset"> Cancel </button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>

ClaimBaseTest.Web/Views/ProjectLink/ViewActiveProjectLink.cshtml
@model CodeGen.Model.ProjectMaster.ViewProjectLink
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewData["Title"] = "Active Global Link";
}

@section Scripts {

    <script>
        $(document).ready(function () {
            $('#example1').DataTable();
        });
    </script>
    <script>
        function check_uncheck_checkbox(isChecked) {
            if (isChecked) {
                $('input[name="chkbox"]').each(function () {
                    this.checked = true;
                });
            }
            else {
                $('input[name="chkbox"]').each(function () {
                    this.checked = false;
                });
            }
        }
        function ClearField() {
            $('input[type=checkbox]').prop('checked', false);
        }
        function validateForm() {
            if ($('#example1 :checked').length == 0) {
                alert("No record selected for Inactive!");
                return false;
            }
            else {
                return confirm('Are you sure you want to Mark As In-Active?');
            }
        }
           $(function () {
            $("#btnReset").bind("click", function () {
                  var url = '@Url.Action("ViewActiveProjectLink", "ProjectLink")';
                window.location.href = url;

            });
        });

    </script>
}
@{
    if (TempData["CommandStatus"] != null)
    {
        <script type="text/javascript">
          alert('@(TempData["CommandStatus"])');
        </script>
    }

}
<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Active Project Link</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Project Link</li>
                    <li class="breadcrumb-item active" aria-current="page">Active Project Link</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link " asp-controller="ProjectLink" asp-action="AddProjectLink">Add</a>
                        <a class="nav-item nav-link active" asp-controller="ProjectLink" asp-action="ViewActiveProjectLink">Active</a>
                        <a class="nav-item nav-link" asp-controller="ProjectLink" asp-action="ViewInActiveProjectLink">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>

                <div class="card-body">
                    @if (Model.ViewProjectLinkDetailsmodel.Count != 0)
                    {
                        <form id="frmMarkInactive" data-parsley-validate novalidate method="post" asp-action="MarkAsInActive"
                              asp-controller="ProjectLink" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                            <div class="table-responsive">
                                <table data-toggle="table" class="table table-hover table-bordered table-padding" id="example1">

                                    <thead>
                                        <tr>
                                            <th width="10px"><input type="checkbox" id="checkBoxAll" onclick="check_uncheck_checkbox(this.checked)" /></th>
                                            <th width="10px">SL#</th>
                                            <th width="100px">Project Name</th>
                                            <th width="20px">Edit</th>


                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.ViewProjectLinkDetailsmodel.Count != 0)
                                        {
                                            @foreach (var proj in Model.ViewProjectLinkDetailsmodel.Select((x, i) => new { Data = x, Index = i + 1 }))
                                            {

                                                <tr>
                                                    <td><input type="checkbox" name="chkbox" value="@proj.Data.INTPROJECTLINKID" /></td>
                                                    <td>@proj.Index</td>
                                                    <td>@Html.DisplayFor(modelItem => proj.Data.NVCHPROJECTLINKNAME)</td>

                                                    <td>
                                                        <a class="btn btn-info btn-sm" data-toggle="tooltip" data-original-title="Edit" asp-controller="ProjectLink" asp-action="EditActiveProjectLink" asp-route-id="@proj.Data.INTPROJECTLINKID">
                                                            <i class="icon-edit1"></i>
                                                        </a>

                                                    </td>

                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr style="text-align: center;font-size: x-large;font-weight: bolder;">
                                                <td colspan='6' align='center'> No records found!</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                                <button type="submit" name="submitButton" id="btnsubmit" class="btn btn-primary mb-1t white-text" title="Mark AS Inactive" value="submit">Mark AS Inactive</button>
                                <button type="button" value="Reset" class="btn btn-danger" onclick="return ClearField();"><span>Reset</span></button>
                            </div>
                        </form>
                    }
                    else

                    {

                        <h4>Record Not Found</h4>
                    }

                    <div class="table-responsive">
                    </div>
                </div>


            </div>

        </div>

    </div>
</div>