ClaimBaseTest.Web/Controllers/AdminConsole_Controllers/GlobalLinkController.cs
using CodeGen.Model.GlobalLink;
using CodeGen.Repository.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace ClaimBaseTest.Web
{
    public class GlobalLinkController : Controller
    {



        //
        // GET: /GlobalLink/

        Global objGloba = new Global();
     
        public static string StrOL;
        private const int defaultPageSize = 10;
        private readonly IGblLinkServiceProvider _gblLinkService;
        private readonly IProjectLinkServiceProvider _projectLinkService;
        GlobalModel model = new GlobalModel();

        public GlobalLinkController(IGblLinkServiceProvider gblLinkService, IProjectLinkServiceProvider projectLinkService)
        {
            _gblLinkService = gblLinkService;
            _projectLinkService = projectLinkService;
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AddGlobalLink()
        {
            //var s = HttpContext.Session.GetString("UserName");
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                ViewGlobal g = new ViewGlobal();
                model.GlobalModelList = (await _gblLinkService.GetMaxId()).ViewGlobalLinkDetailsmodel.ToList();
                g.GMAxid = model.GlobalModelList[0].GMAxid; //_gblLinkService.GetGlobalLinkMaxId();
                //g.CreatedBy = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                g.ProjectList = (await _projectLinkService.GetAllActiveProjectLink()).ViewProjectLinkDetailsmodel.ToList();
                return View(g);
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}


        }
        #region Add Global Link
        [HttpPost]
        public IActionResult AddGlobalLink(ViewGlobal objglobal)
        {
            try
            {
             
                var Result = _gblLinkService.AddGlobalLink(objglobal);
               return RedirectToAction("ViewGlobalLinkActive", new { Status = Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion
        [HttpGet]
        public async Task<IActionResult> ViewGlobalLinkActive(string Status)
        {
            //GlobalModel model = new GlobalModel();
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                try
                {
                model.GlobalModelList = (await _gblLinkService.GetAllActiveGlobalLink()).ViewGlobalLinkDetailsmodel.ToList();
                if (Status == "1")
                {
                    TempData["CommandStatus_S"] = Status;

                }
                else if (Status == "2")
                {
                    TempData["CommandStatus_U"] = Status;

                }
                else if (Status == "4")
                {
                    TempData["CommandStatus_A"] = Status;

                }
                else if (Status == "5")
                {
                    TempData["CommandStatus_AC"] = Status;

                }
                else if (Status == "6")
                {
                    TempData["CommandStatus_INA"] = Status;

                }
                else if (Status == "7")
                {
                    TempData["CommandStatus_AU"] = Status;

                }
                //TempData["CommandStatus"] = Status;
                return View(model);

            }
            catch (Exception ex)
            {

                throw ex;
            }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}



        }
        [HttpGet]
        public async Task<IActionResult> ViewGlobalLinkInActive()
        {
            //GlobalModel model = new GlobalModel();
            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{
                try
            {
                model.GlobalModelList = (await _gblLinkService.GetAllInActiveGlobalLink()).ViewGlobalLinkDetailsmodel.ToList();
                return View(model);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}

        }
        public async Task<IActionResult> EditActiveGlobalLink(int id)
        {

            //if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            //{ 
            try
            {
                model.GlobalModelList = (await _gblLinkService.GetById(id)).ViewGlobalLinkDetailsmodel.ToList();


                ViewGlobal m = new ViewGlobal();
                m.ProjectList = (await _projectLinkService.GetAllActiveProjectLink()).ViewProjectLinkDetailsmodel.ToList();

                    //var globalresult = _gblLinkService.GetGlobalLinkById(id).Result;
                m.intGLinkID = model.GlobalModelList[0].intGLinkID; ;
                m.nvchGLinkName =   model.GlobalModelList[0].nvchGLinkName;
                m.VCHICONCLASS = model.GlobalModelList[0].VCHICONCLASS;
                m.intSortNum =model.GlobalModelList[0].intSortNum;
                //m.updatedBy = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
                m.INTPROJECTLINKID = model.GlobalModelList[0].INTPROJECTLINKID;
                return View(m);

            }
            catch (Exception ex)
            {
                throw ex;
            }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}
        }
        #region Update Global Link
        [HttpPost]
        public IActionResult EditGlobalLink(ViewGlobal objglobal)
        {
            try
            {

                var Result = _gblLinkService.EditGlobalLink(objglobal);

                objglobal.resultmsg = Result;
                return RedirectToAction("ViewGlobalLinkActive", new { Status = Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion

        #region Delete Global Link
      
        public IActionResult DeleteGlobalLink(int id)
        {
            try
            {

                var Result = _gblLinkService.DeleteGlobalLink(id,Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                return RedirectToAction("ViewGlobalLinkActive", new { Status = "Record " + Result });
                // return RedirectToAction("AddGlobalLink", new { Status = "Record " + Result });

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion

        #region Mark As InActive Global Link
        [HttpPost]
        public IActionResult MarkAsInActive(string[] chkbox, int updatedby)
        {
            try
            {
                string primarylinkId = string.Join(",", chkbox);
                var Result = String.Empty;
                foreach (string Id in chkbox)
                {
                     Result = _gblLinkService.DeleteGlobalLink(Convert.ToInt32(Id), Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                }
                return RedirectToAction("ViewGlobalLinkActive", new { Status = Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
        public IActionResult MarkAsActive(string[] chkbox, int updatedby)
        {
            try
            {
                string primarylinkId = string.Join(",", chkbox);
                var Result = String.Empty;
                foreach (string Id in chkbox)
                {
                    Result = _gblLinkService.MarkActiveGlobalLink(Convert.ToInt32(Id), Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                }
                return RedirectToAction("ViewGlobalLinkActive", new { Status = Result });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
      
        public IActionResult SlnoModifyData([FromBody] GlobalModel objGlobalModel)
        {
            try
            {
                var Result = String.Empty;
                string[] Globalslnolist = objGlobalModel.slnomodifyList.Split(new char[] { '^' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (string item in Globalslnolist)
                {
                    string[] slno = item.Split('|');
                    Result = _gblLinkService.ModifySlnoGlobalLink(Convert.ToInt32(slno[0]), Convert.ToInt32(slno[1]),  Convert.ToInt32(HttpContext.Session.GetString("UserId")));

                }

                return Json(Result);


            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        
        #endregion





        


    }
}

ClaimBaseTest.Web/Views/Shared/Components/AdminConsole/AdminConsoleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using CodeGen.Repository.Repositories.Interfaces;
namespace ClaimBaseTest.Web.Views.Shared.Components.AdminConsole
{
    public class AdminConsoleViewComponent : ViewComponent
    {
        private readonly ISetPermissionServiceProvider _SetPermission;
        private readonly IConfiguration _config;

        public AdminConsoleViewComponent(ISetPermissionServiceProvider SetPermission, IConfiguration Configuration)
        {
            _SetPermission = SetPermission;
            _config = Configuration;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //Commented (This is only for Basic Login) 
            //var userid = HttpContext.Session.GetInt32("userId");
            //var desgid = HttpContext.Session.GetInt32("DesgId");

            // Retrieve INTUSERID and INTDESIGNATIONID claims from the current user's identity
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "INTUSERID");
            var desgIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "INTDESIGNATIONID");

            // Check if claims exist and convert them to integers
            int? userId = userIdClaim != null ? Convert.ToInt32(userIdClaim.Value) : null;
            int? desgId = desgIdClaim != null ? Convert.ToInt32(desgIdClaim.Value) : null;


            var PId = _config.GetValue<int>("MySettings:ProjectId");
            var results = _SetPermission.GetLinkAccessByUserId(Convert.ToInt32(userId), PId, Convert.ToInt32(desgId));
          /*  var plinkValue = HttpContext.Request.Query["Plink"].ToString();
            var btn= _SetPermission.GetButtondefaultTab(plinkValue);
            ViewBag.Btnid = Convert.ToUInt32(btn);
            var btnid= _SetPermission.GetButtondefaultTab(plinkValue);
            ViewBag.Tabid = _SetPermission.GetdefaultTab(plinkValue, btnid);*/
            var Data = results.ToList();
            if (HttpContext.Request.Query["Glink"].ToString() != "")
            {
                Data.ForEach(c => c.Aglinkid = Convert.ToInt32(HttpContext.Request.Query["Glink"]));
                //TempData["Glink"] = HttpContext.Request.Query["Glink"].ToString();
                //TempData.Keep();
            }
            if (HttpContext.Request.Query["Plink"].ToString() != "")
            {
                Data.ForEach(c => c.Aplinkid = Convert.ToInt32(HttpContext.Request.Query["Plink"]));
                //TempData["Plink"] = HttpContext.Request.Query["Plink"].ToString();
                //TempData.Keep();
            }
            return View("default", results);
        }
    }
}

ClaimBaseTest.Web/Views/Shared/Components/AdminConsole/ButtonTabViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using CodeGen.Repository.Repositories.Interfaces;
using CodeGen.Model.User;
using System.Security.Claims;

namespace AdConsole11.Web.Views.Shared.Components.AdminConsole
{
    public class ButtonTabViewComponent : ViewComponent
    {
        private readonly ISetPermissionServiceProvider _SetPermission;
        private readonly IConfiguration _config;
        public ButtonTabViewComponent(ISetPermissionServiceProvider SetPermission, IConfiguration Configuration)
        {
            _SetPermission = SetPermission;
            _config = Configuration;
        }

        public async Task<IViewComponentResult> InvokeAsync(string plinkValue, string btnid)
        {
            try
            {
                var tabid = "";
                if (Request.Query["Plink"].ToString().Length > 0)
                {

                    tabid = Request.Query["Tabid"].ToString();
                    plinkValue = Request.Query["Plink"].ToString();
                    btnid = Request.Query["Buttonid"].ToString();


                    if (btnid == "")
                    {
                        btnid = _SetPermission.GetButtondefaultTab(plinkValue);
                    }

                    if (tabid == "")
                    {
                        tabid = _SetPermission.GetdefaultTab(plinkValue, btnid);
                    }
                }

                //plinkValue = Request.Query["Plink"].ToString();
                //btnid=Request.Query["Buttonid"].ToString();
                //plinkValue = HttpContext.Request.Query["Plink"].ToString(); //both are same

                if(btnid!=null)
                {
                    var claimsPrincipal = HttpContext.User;
                    var intDesignationIdClaim = claimsPrincipal.FindFirst("INTUSERID")?.Value;
                    var userid = HttpContext.Session.GetInt32("userId");
                    var desgid = HttpContext.Session.GetInt32("DesgId");
                    var PId = _config.GetValue<int>("MySettings:ProjectId");
                    var results = _SetPermission.GetButtonWithTabAccess(plinkValue, btnid, Convert.ToInt32(intDesignationIdClaim));
                    ViewBag.Btnid = _SetPermission.GetButtondefaultTab(plinkValue);
                    ViewBag.Tabid = _SetPermission.GetdefaultTab(plinkValue, btnid);
                    ViewBag.BtnTab = results;
                    ViewBag.ClickTabId = tabid;
                    ViewBag.ClickBtnId = btnid;
                    var Data = results.ToList();
                    return View("ButtonWithTab", results);
                }
                else
                {
                    //var redirectToUrl = Url.Action("DenayPermission", "Home");
                    ////return View("Redirect1", (object)redirectToUrl);
                    //return View("/Views/Shared/Components/ButtonTab/Redirect1.cshtml");
                    var results = _SetPermission.GetButtonWithTabAccess(plinkValue, "", 0);
                    return View("ButtonWithTab", results);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}






#region Old Code by Anshuman
//using Microsoft.AspNetCore.Mvc;
//using CodeGen.Repository.Repositories.Interfaces;
//using CodeGen.Model.User;

//namespace ClaimBaseTest.Web.Views.Shared.Components.AdminConsole
//{
//    public class ButtonTabViewComponent : ViewComponent
//    {
//        private readonly ISetPermissionServiceProvider _SetPermission;
//        private readonly IConfiguration _config;
//        public ButtonTabViewComponent(ISetPermissionServiceProvider SetPermission, IConfiguration Configuration)
//        {
//            _SetPermission = SetPermission;
//            _config = Configuration;
//        }
//        public async Task<IViewComponentResult> InvokeAsync(string plinkValue, string btnid)
//        {
//            if (Request.Query["Plink"].ToString().Length > 0)
//            {
//                plinkValue = Request.Query["Plink"].ToString();
//                btnid = Request.Query["Buttonid"].ToString();
//                ViewBag.ClickBtnId= Request.Query["Buttonid"].ToString();
//                if (btnid == "")
//                {
//                    btnid = _SetPermission.GetButtondefaultTab(plinkValue);
//                }
//            }

//            //plinkValue = Request.Query["Plink"].ToString();
//            //btnid=Request.Query["Buttonid"].ToString();
//            //plinkValue = HttpContext.Request.Query["Plink"].ToString(); //both are same

//            var userid = HttpContext.Session.GetInt32("userId");
//            var desgid = HttpContext.Session.GetInt32("DesgId");
//            var PId = _config.GetValue<int>("MySettings:ProjectId");
//            var results = _SetPermission.GetButtonWithTabAccess(plinkValue, btnid);
//            ViewBag.BtnTab = results;
//            ViewBag.Btnid = _SetPermission.GetButtondefaultTab(plinkValue);

//            var Data = results.ToList();

//            //ViewBag.BtnTab = _userService.GetAllUsers(new User { ActionCode = "VF" });

//            return View("ButtonWithTab", results);
//        }
//    }
//}
#endregion

ClaimBaseTest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>Admin</title>*@
    <meta name="keywords" content="ADSYS" />
    <meta name="description" content="ADSYS" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/icons.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/custom.css" rel="stylesheet">
    @*//imp for structur*@
    <link href="~/css/dashboard.css" rel="stylesheet">
    <link href="~/css/slimscrollbar.min.css" rel="stylesheet">
    <script src="~/js/chartist-plugin-tooltip.js"></script>
    <script src="~/js/chartist.min.js"></script>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="javascript:void:(0);">

                <h1>
                </h1>
            </a>
            <a class="nav-toggle-btn">
                <span></span>
            </a>

            <div class="navbar-collapse justify-content-end collapse" id="basicExampleNav">
                <!-- Links -->
                <ul class="navbar-nav">
                    @using System.Security.Claims  @*This is for Claims Login*@
                    @{
                        var userName = Context.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
                    }
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle welcome" data-toggle="dropdown" href="Javascript:void(0);">
                            Welcome
                            <span class="bg-danger">
                                @userName
                                @*@HttpContextAccessor.HttpContext.Session.GetString("UserName")*@  @*This is for Basic Login*@
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link logout" href="Javascript:void(0);"><i class="icon-log-out1"></i></a>
                    </li>
                    <!-- Dropdown -->
                </ul>
                <!-- Links -->
            </div>
            <!-- Collapsible content -->
        </nav>
        <!--/.Navbar-->
    </header>
    <div class="logout-modal">
        <div class="logou-container text-center">
            <div class="container">
                <h3>Do you really want to log out?</h3>
                @*<a class="btn btn-mint" asp-controller="CodeGenLogin" asp-action="Userlogin">Yes</a>*@
                <a class="btn btn-mint" asp-area="" asp-controller="Home" asp-action="LogOut">Yes</a>
                <a class="btn btn-danger nologout">No</a>
            </div>
        </div>
    </div>
    <div class="page-container">
        <div class="sidemenu" id="dashboard">
            <div class="user-profile">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <span> </span>
                </a>
            </div>
            <div class="clearfix">
            </div>
            <ul class="navbar">
                <div class="navbar-collapse justify-content-end" id="basicExampleNav">
                    <ul class="navbar-nav" id="AdConsole">
                        @await Component.InvokeAsync("AdminConsole")
                    </ul>
                </div>
            </ul>
        </div>

        <div class="mainpanel">
            <div>
                @await Component.InvokeAsync("ButtonTab", new { plinkValue = "", btnid = "" })
            </div>
            <div class="section">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="page-footer no-padding white blue-text hide">
        <div class="footer-copyright">
            <div class="container">
                &copy; 2023 All right reserved
                <a class="right" href="javascript:void(0);">Developed by CSM</a>
            </div>
        </div>
    </footer>
    <div class="setting-box">
        <div class="profile-details">
            <a class="setting-close" href="javascript:void(0)"><span class="icon-x1"></span></a>
            <div class="change__list">
                <ul>

                    <li>
                        @*<a href="#" asp-controller="CodeGenLogin" asp-action="LogOut" data-toggle="tooltip" data-placement="top" data-original-title="Sign out">
                                <span class="icon-log-out1"></span>
                            </a>*@
                        @*<a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Sign out">
                                <span class="icon-log-out1"></span>
                            </a>*@
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <link href="~/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <script src="~/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/slimscrollbar.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>
</html>

ClaimBaseTest.Web/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>Admin</title>*@
    <meta name="keywords" content="ADSYS" />
    <meta name="description" content="ADSYS" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/icons.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/custom.css" rel="stylesheet">
    @*//imp for structur*@
    <link href="~/css/dashboard.css" rel="stylesheet">
    <link href="~/css/slimscrollbar.min.css" rel="stylesheet">
    <script src="~/js/chartist-plugin-tooltip.js"></script>
    <script src="~/js/chartist.min.js"></script>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="javascript:void:(0);">

                <h1>
                </h1>
            </a>
            <a class="nav-toggle-btn">
                <span></span>
            </a>

            <div class="navbar-collapse justify-content-end collapse" id="basicExampleNav">
                <!-- Links -->
                <ul class="navbar-nav">
                    @using System.Security.Claims  @*This is for Claims Login*@
                    @{
                        var userName = Context.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
                    }
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle welcome" data-toggle="dropdown" href="Javascript:void(0);">
                            Welcome
                            <span class="bg-danger">
                                @userName
                                @*@HttpContextAccessor.HttpContext.Session.GetString("UserName")*@  @*This is for Basic Login*@
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link logout" href="Javascript:void(0);"><i class="icon-log-out1"></i></a>
                    </li>
                    <!-- Dropdown -->
                </ul>
                <!-- Links -->
            </div>
            <!-- Collapsible content -->
        </nav>
        <!--/.Navbar-->
    </header>
    <div class="logout-modal">
        <div class="logou-container text-center">
            <div class="container">
                <h3>Do you really want to log out?</h3>
                @*<a class="btn btn-mint" asp-controller="CodeGenLogin" asp-action="Userlogin">Yes</a>*@
                <a class="btn btn-mint" asp-area="" asp-controller="Home" asp-action="LogOut">Yes</a>
                <a class="btn btn-danger nologout">No</a>
            </div>
        </div>
    </div>
    <div class="page-container">
        <div class="sidemenu" id="dashboard">
            <div class="user-profile">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <span> </span>
                </a>
            </div>
            <div class="clearfix">
            </div>
            <ul class="navbar">
                <div class="navbar-collapse justify-content-end" id="basicExampleNav">
                    <ul class="navbar-nav" id="AdConsole">
                        @await Component.InvokeAsync("AdminConsole")
                    </ul>
                </div>
            </ul>
        </div>

        <div class="mainpanel">
            <div class="section">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="page-footer no-padding white blue-text hide">
        <div class="footer-copyright">
            <div class="container">
                &copy; 2023 All right reserved
                <a class="right" href="javascript:void(0);">Developed by CSM</a>
            </div>
        </div>
    </footer>
    <div class="setting-box">
        <div class="profile-details">
            <a class="setting-close" href="javascript:void(0)"><span class="icon-x1"></span></a>
            <div class="change__list">
                <ul>
                    <li>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <link href="~/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <script src="~/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/slimscrollbar.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>
</html>